sudo: required

language: generic

services:
- docker

arch:
  packages:
  - openmpi
  - cpplint
  script:
  - ./test.sh
  - ./lint.sh

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
